name: sim2real_robot_identification_env
# Force ROS 2 to use localhost at startup for safety.
# This value can still be overridden after activating the environment.
variables:
  ROS_LOCALHOST_ONLY: "1"
channels:
- conda-forge
- nvidia
- robostack-staging
dependencies:
- pip
- python
- numpy
- ros-humble-desktop
- ros-humble-rmw-cyclonedds-cpp
- ros-humble-rosidl-generator-dds-idl
- ros-humble-plotjuggler-ros
- compilers 
- cmake 
- pkg-config 
- make 
- ninja 
- colcon-common-extensions 
- catkin_tools 
- rosdep
- tqdm
- gymnasium
- pip:
  - readchar
  - torch
  - mujoco==3.10.0
  - tabulate
  - plotly
  - mediapy
  - scipy